AWSTemplateFormatVersion: '2010-09-09'

Description: Creates an Internet Gateway and attaches it to the VPC.

Parameters:
  VPCName:
    Description: The name of the VPC being created.
    Type: String
    Default: VPC Public and Private with NAT

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: Public
        - Key: Name
          Value: !Join
            - ''
            - - !Ref VPCName
              - '-IGW'

  GatewayToInternet:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !ImportValue VPCId
      InternetGatewayId: !GetAtt InternetGateway.InternetGatewayId

Outputs:
  InternetGatewayId:
    Description: Id of Internet Gateway
    Value: !Ref InternetGateway
    Export:
      Name: InternetGatewayId